### ISSUE TITLE
[CM][CI] Enable regular CI for TVM

### ISSUE THREAD

**Issue by KJlaccHoeUM9l** [Deelvin/ck#4] opened 2023-01-29 17:15 UTC
The problems described in #1 arose due to the fact that the pipeline for TVM was launched only when opening PRs against branches `test` and `dev` ([link](https://github.com/mlcommons/ck/blob/master/.github/workflows/test-cm-tutorial-tvm.yml)). 
This is due to the fact that this pipeline uses building of TVM from the source code, which takes ~50 minutes. It was too long to run this pipeline against `master` branch.
Recently, to avoid long build times, a new pipeline has been added that uses `pip` to install a pre-built TVM. However, this pipeline only runs on `test` branch ([link](https://github.com/mlcommons/ck/blob/master/.github/workflows/test-cm-tutorial-tvm-pip.yml)).

It is necessary to check this pipeline and make it run against `master` branch.

**Comment by Ailurus1** [comment] 2023-02-08 17:52
I tried to run `tests/tutorials/test_tvm_pip.py`, which executes in CI check, but got unexpected error:
```
CM error: Please rerun the last CM command with --env.IMAGENET_PATH={path the folder containing full ImageNet images} or envoke cm run script "get val dataset imagenet" --input={path to the folder containing ImageNet images}!
```
This error occurs only in submission mode and not only with tvm-onnx backend. I guess that it may work this way any time we run inference with imagenet dataset with variation `_full`. The same script works fine without submission mode.
This error appears during processing [customize.py](https://github.com/mlcommons/ck/tree/master/cm-mlops/script/get-dataset-imagenet-val/customize.py) in `get-dataset-imagenet-val` when it tries to get path to full imagenet dataset. 

Perhaps the error occurred after [this commit](https://github.com/mlcommons/ck/commit/0a1691e5a16b343b887911cd9a241b783257dcaa#diff-cc292059841186bf230cadbd1b631f80f201cd3b34a03d08b85497e4f0e78d9c) when the variation `_full` has become default variation for submission mode instead of `_short` (which is still also [marked](https://github.com/mlcommons/ck/blob/cc7d9ac65b77e74c353f5d1172c26fadbcc3dde9/cm-mlops/script/run-mlperf-inference-app/_cm.json#L144) as default but in a different way and CM chooses `_full`).

So, the problem is that CM cannot find path to imagenet from `CM_INPUTS` or `IMAGENET_PATH` variables during processing [customize.py](https://github.com/mlcommons/ck/tree/master/cm-mlops/script/get-dataset-imagenet-val/customize.py) from `get-dataset-imagenet-val` while running MLPerf inference for models (ResNet50) on imagenet in submission mode

**Comment by Ailurus1** [comment] 2023-02-09 06:30
@KJlaccHoeUM9l

**Comment by Ailurus1** [comment] 2023-02-13 19:22
I opened a [PR](https://github.com/Deelvin/ck/pull/10) where tvm-onnx CI check for ResNet50 inference is enabled against master branch and looks like it works [correctly](https://github.com/Deelvin/ck/actions/runs/4170689908/jobs/7219896811). 
Because of the problem mentioned above and in order to reduce the working time of this workflow the `_short` variation was specified for test in submission mode. Also, I removed some default batchsizes that were set for tvm-onnx and tvm-pytorch backend in [this](https://github.com/mlcommons/ck/commit/72d4730dea23be00e78c3378d5d72b9008bd1888) commit as it caused an old error with model shapes mismatch so without it workflow seems to work properly, at least all CI checks have been passed

**Comment by Ailurus1** [comment] 2023-02-20 06:13
I think it can be closed as [this PR](https://github.com/mlcommons/ck/pull/667) has been merged

**Closed as completed by Ailurus1** 2023-02-20 06:13 UTC
Labels: enhancement
